-- Prism PS2 Launcher - core/paths.lua
-- Resolving paths: roots, ROM folders, titles, artwork, wLaunchELF.
-- Split from the original system.lua (RETROLauncher, Spaghetticode / Boon Tobias).
-- Definitions only, except where noted; loaded by System/system.lua in boot order.

--- First root where the given relative path exists (starts with "/"). ------------------
function RAIZ(rel)
	for i = 1, #RAICES do
		if doesFileExist(RAICES[i] .. rel) then return RAICES[i] end
	end
	return RAICES[1]
end

--- Source of each game found: ORIGEN["identidad|nombre"] = root. ---------------------
--- Search on the CD/DVD drive ("cdfs:"). ---------------------------------------------
--- Spaghetticode (the project author) reports that the program hangs if it is launched
--- from a wLaunchELF that has already loaded the CD/DVD module (Slim console), and that
--- the problem goes away if everything to do with searching the drive is skipped.
--- false = leave the drive alone. true = original behaviour.
BUSCAR_CDVD = false

--- Folder names in EmulationStation / Batocera style, per system. --------------------
--- They are accepted as well as the fork's own "Roms/Roms <sistema>" structure, both in
--- "<raiz>/roms/<alias>" and in "<unidad>/roms/<alias>" (Batocera layout).
ES_ALIAS = {
	{"megadrive", "genesis", "md"},
	{"mastersystem", "sms"},
	{"gamegear", "gg"},
	{"nes", "famicom", "fds"},
	{"gb", "gameboy"},
	{"gbc", "gameboycolor"},
	{"gba", "gameboyadvance"},
	{"atari2600"},
	{"lynx", "atarilynx"},
	{"sg1000", "sg-1000"},
	{"ngp", "ngpc", "neogeopocket"},
	{"snes", "sfc", "supernintendo"},
}

--- Real path of a ROM: the directory recorded during the scan if there is one, else
--- the fork's own structure resolved against the roots.
function RUTA_ROM(identidad, sistema, nombre)
	local clave = tostring(identidad) .."|".. nombre
	if ORIGEN_DIR ~= nil and ORIGEN_DIR[clave] ~= nil then
		return ORIGEN_DIR[clave] .. nombre
	end
	return RUTA("/Roms/Roms ".. sistema .."/".. nombre)
end

--- Real game titles. TITULOS["identidad|fichero"] = title. --------------------------
--- Generated by the "HelperScripts/BatoceraGamelistandMediaCopier.py" script, one "titles.txt" per
--- folder, out of the gamelist.xml of Batocera / Recalbox / EmulationStation.
--- Format of each line: file_name|Game title
TITULOS = {}
TITULOS_LEIDOS = {}

function cargar_titulos(directorio, identidad)
	if directorio == nil then return end
	if TITULOS_LEIDOS[directorio] == true then return end
	TITULOS_LEIDOS[directorio] = true

	local ruta = directorio .."/titles.txt"
	if doesFileExist(ruta) == false then return end
	pcall(function()
		local fd = System.openFile(ruta, FREAD)
		local tam = System.sizeFile(fd)
		System.seekFile(fd, 0, SET)
		local datos = System.readFile(fd, tam)
		System.closeFile(fd)
		for linea in string.gmatch(datos, "[^\r\n]+") do
			local corte = string.find(linea, "|", 1, true)
			if corte ~= nil then
				local fichero = string.sub(linea, 1, corte-1)
				local titulo  = string.sub(linea, corte+1)
				if fichero ~= "" and titulo ~= "" then
					TITULOS[tostring(identidad) .."|".. fichero] = titulo
				end
			end
		end
	end)
end

--- Name to display: the real title if known, otherwise the file name with its
--- extension trimmed off, as the original program does.
function NOMBRE_VISIBLE(identidad, nombre, desde)
	if nombre == nil then return "" end
	local t = TITULOS[tostring(identidad) .."|".. nombre]
	if t == nil then
		local limpio = nombre
		while string.sub(limpio, -1) == " " do limpio = string.sub(limpio, 1, -2) end
		t = string.match(limpio, "^(.*)%.[^%.]+$") or limpio
	end
	if desde ~= nil and desde > 1 then return string.sub(t, desde) end
	return t
end

--- RetroArch cores. -----------------------------------------------------------------
--- "LibretroPS2Files/cores/" takes an unpacked nightly exactly as it comes, and it is
--- the ONLY place cores are looked for. The per-system copies that used to sit in
--- "System/RetroarchPS2/<sistema>/cores/" are deleted: they were the same ten files
--- repeated thirteen times, 36 MB.
--- ALL roots are searched, so the folder can live on the exFAT disk.
--- "ruta_original" is kept as a fallback in case someone puts those copies back.
--- uLaunchELF, whatever the ELF is called. -------------------------------------------
--- Every version ships under a different name -- "WLE.ELF", "WLE-R3Z.ELF",
--- "WLE-R3Z-DS34.ELF"... -- so looking for a fixed name breaks as soon as the
--- user updates. The first ".elf" in the folder is taken.
--- A name starting with "_" is disabled on purpose: it is the mark the menu uses
--- to hide the application from the list without deleting it.
--- Returns (path, name, disabled) or nil.
function RUTA_WLE(incluir_desactivado)
	local dir = System.currentDirectory() .."/uLaunchELF"
	local lista = System.listDirectory(dir)
	if lista == nil then return nil end
	local reserva, reserva_n = nil, nil
	for i = 1, #lista do
		local n = lista[i].name
		if lista[i].directory == false and string.lower(string.sub(n, -4)) == ".elf" then
			if string.sub(n, 1, 1) == "_" then
				if reserva == nil then reserva, reserva_n = dir .."/".. n, n end
			else
				return dir .."/".. n, n, false
			end
		end
	end
	if incluir_desactivado == true and reserva ~= nil then
		return reserva, reserva_n, true
	end
	return nil
end

--- This fork's folder names, under "Roms/". -----------------------------------------
--- Scanning for applications at the ROOT of each drive. -------------------------------
--- The APPS list used to be searched, besides in "APPS/" and "Roms/APPS", in the root
--- of the disk, of card mc0: and of mc1:, going ONE LEVEL into every folder it
--- found there. On a disk that also serves OPL that means listing "ART",
--- "THM", "CHT", "$RECYCLE.BIN" and "System Volume Information", which hold thousands
--- of files each: boot stalled right there, on system 13.
--- At false the applications are looked for only where they belong: "APPS/" on each
--- drive, "mc0:/APPS", "mc1:/APPS" and "Roms/APPS". At true the full scan comes back.
APPS_RAIZ_ON = false

ROMS_DIR = {
	"megadrive", "mastersystem", "gamegear", "nes", "gb", "gbc", "gba",
	"atari2600", "lynx", "sg1000", "ngp", "snes",
	"APPS", "psx", "ps2",
}

--- System files, grouped in "Bios/" at the launcher root. ---------------------------
--- The historic locations are kept as a fallback.
function RUTA_BIOS(fichero, respaldo)
	local actual = System.currentDirectory()
	local cand = actual .."/Bios/".. fichero
	if doesFileExist(cand) then return cand end
	if respaldo ~= nil and doesFileExist(respaldo) then return respaldo end
	return cand
end

--- File name from a path. -----------------------------------------------------------
function nombre_fichero(ruta)
	if ruta == nil then return "" end
	local i = string.len(ruta)
	while i > 0 and string.sub(ruta, i, i) ~= "/" do i = i - 1 end
	return string.sub(ruta, i+1)
end

--- Real extensions of each system, to cross them with the ones each core declares.
--- "zip" and "bin" are missing on purpose: they tell nothing apart. Eight of the cores
--- installed declare "bin" (stella2014, gpsp, o2em, gearcoleco, freeintv, smsplus...), so
--- including it would pass almost any core as good for almost any system.
SISTEMA_EXTEN = {
	{"gen", "smd", "md"}, {"sms"}, {"gg"}, {"nes", "fds", "unf"},
	{"gb"}, {"gbc"}, {"gba"}, {"a26"}, {"lnx", "lyx"}, {"sg"},
	{"ngc", "ngp", "npc"}, {"sfc", "smc"},
}

MEDIA_ALIAS = {
	"megadrive", "mastersystem", "gamegear", "nes", "gb", "gbc", "gba",
	"atari2600", "lynx", "sg1000", "ngp", "snes",
	"APPS", "psx", "ps2",
}

--- Index of the media folders. -------------------------------------------------------
--- The manual warns (page 46): checking whether an image exists in a folder of 500
--- items is not the same as looking for it in one of over 1000. Every change of
--- selection asked for up to six different paths, one call to the file system
--- for each, and this fork has multiplied the roots to explore.
--- Here the folder is listed ONCE and after that the check is a table lookup,
--- free. The index is emptied when a list is rebuilt, which is when the
--- content may have changed.
MEDIA_INDICE = {}

function media_indice(directorio)
	local idx = MEDIA_INDICE[directorio]
	if idx ~= nil then return idx end
	idx = {}
	local c = System.listDirectory(directorio)
	if c ~= nil then
		for i = 1, #c do
			if c[i].directory == false then idx[c[i].name] = true end
		end
	end
	MEDIA_INDICE[directorio] = idx
	return idx
end

function media_indice_olvidar()
	MEDIA_INDICE = {}
end

--- Locating covers and screenshots. -------------------------------------------------
--- This fork looks FIRST next to the ROM itself, which lets the media for the
--- games on the exFAT disk live on the exFAT disk:
---   <rom folder>/media/covers/<file without extension>.png
---   <rom folder>/media/screenshots/<file without extension>.png
--- If there is nothing, the program's historic location is used:
---   <launcher>/Multimedia/Covers/Covers <Sistema>/<file without extension>.png
function RUTA_MEDIA(tipo, identidad, sistema, nombre, base)
	if nombre == nil then return "" end
	local carpeta = "covers"
	local clasico = "Covers/Covers "
	if tipo == "screenshot" then
		carpeta = "screenshots"
		clasico = "Screenshots/Screenshots "
	end

	-- 1. "Roms/<alias>/media/..." on each root, IN ORDER: RAICES[1] is always the
	--    boot medium, so the USB wins. A game that lives on the exFAT disk
	--    uses the cover from the USB if it is there, which allows all the images
	--    to be centralised on the stick without duplicating them on the disk.
	if tipo == "cover" then MEDIA_DIAG = {} end
	local function probar(dir, fichero)
		local hay = media_indice(dir)[fichero] == true
		if tipo == "cover" and #MEDIA_DIAG < 8 then
			table.insert(MEDIA_DIAG, (hay and "[ok]   " or "[FALTA] ") .. dir .."/".. fichero)
		end
		return hay
	end

	-- PS1 gathers two formats under the same identity, and their images can be in
	-- the folder of either one. Both are tried.
	local fichero = base ..".png"
	-- PlayStation: ONE single image folder, "Roms/psx/media", as in
	-- EmulationStation. A PS1 game can be a .VCD in "POPS/" or a folder
	-- in "Ember/games/", and it is the same game with the same cover: stored once.
	local alias = {MEDIA_ALIAS[identidad]}
	if RAICES ~= nil then
		for a = 1, #alias do
			if alias[a] ~= nil then
				for i = 1, #RAICES do
					local dir = RAICES[i] .."/Roms/".. alias[a] .."/media/".. carpeta
					if probar(dir, fichero) then return dir .."/".. fichero end
				end
			end
		end
	end

	-- 2. Next to the ROM itself, wherever that may be.
	local orig = nil
	if ORIGEN_DIR ~= nil then orig = ORIGEN_DIR[tostring(identidad) .."|".. nombre] end
	if orig ~= nil then
		local dir = orig .."media/".. carpeta
		if probar(dir, fichero) then return dir .."/".. fichero end
	end

	-- 3. Historic location, for compatibility with existing installations.
	local dir = base_launcher() .."/Multimedia/".. clasico .. sistema
	probar(dir, fichero)
	return dir .."/".. fichero
end

--- Paths tried for the last cover. They are dumped to the journal on launch,
--- which is the only way to see from the PC what the console really looked at.
MEDIA_DIAG = {}

--- Trace of image loading. ---------------------------------------------------------
--- "Graphics.loadImage" can hang the console with a PNG it does not like or that does
--- not fit in VRAM, and then neither message nor log is left. Here the path is written
--- BEFORE loading it: if the console freezes, the last line of the file names
--- the guilty image. Set to false once it is no longer needed, it writes on every
--- The last image opened, as a witness to a freeze. -----------------------------------
--- If the journal ends on an ART line that says "cargando", the console hung while
--- opening that image: converting or shrinking it settles the case.
--- ART_LOG_ON at false -- which is the normal case -- only keeps it in memory and writes
--- it when something else triggers a dump. At true it writes at once, and then EVERY
--- cover rewrites the whole file: only for hunting down precisely that hang.
ART_LOG_ON = false

function log_art(fase, ruta)
	ART_ULTIMA = tostring(fase) .." -> ".. tostring(ruta)
	if ART_LOG_ON == true then boot_flush() end
end

--- OPL's "ART" folder. It sits at the ROOT of the drive, NOT inside the launcher, and
--- upstream only looked on the boot medium. Here the BDM drives are walked as well,
--- so that "<exFAT disk>/ART" serves the games that live there.
function RUTA_ART(fichero)
	local cand = {}
	local actual = System.currentDirectory()
	local pos = string.find(actual, ":", 1, true)
	if pos ~= nil then table.insert(cand, string.sub(actual, 1, pos)) end
	if BDM_DEVICES ~= nil then
		for i = 1, #BDM_DEVICES do table.insert(cand, BDM_DEVICES[i]) end
	end
	-- OPL's "ART" can hold hundreds of images: it is indexed like the rest.
	for i = 1, #cand do
		if media_indice(cand[i] .."/ART")[fichero] == true then
			return cand[i] .."/ART/".. fichero
		end
	end
	if #cand >= 1 then return cand[1] .."/ART/".. fichero end
	return actual .."/ART/".. fichero
end

--- Global resources (backgrounds, fonts). New location: "Roms/!Prism/",
--- alongside the rest of the content. "Multimedia/Others" is kept as a fallback.
function RUTA_GLOBAL(que)
	local actual = System.currentDirectory()
	local nuevo = actual .."/Roms/!Prism/".. que
	if System.listDirectory(nuevo) ~= nil then return nuevo end
	return actual .."/Multimedia/Others/".. que
end

--- Launcher folder (boot medium). ---------------------------------------------------
function base_launcher()
	return System.currentDirectory()
end

ERROR_DETALLE = nil   -- detail of the last "existe()" failure

--- The error box has only ONE line between the title and the footer. Here a short
--- text is returned (file names only, truncated if need be) and the full version,
--- with the path, is dumped to the journal.
function detalle_falta(etiqueta, base, faltan)
	if faltan == nil or #faltan == 0 then
		log_lanzamiento(etiqueta .."  check failed", {"directory : ".. tostring(base), "(no file identified as missing)"})
		return "Check ".. etiqueta ..": path?"
	end

	local campos = {"expected directory : ".. tostring(base), ""}
	for i = 1, #faltan do
		table.insert(campos, "MISSING : ".. faltan[i])
	end
	log_lanzamiento(etiqueta .."  missing files", campos)

	local corto = "Missing: ".. faltan[1]
	if #faltan >= 2 then corto = corto .." +".. (#faltan-1) end
	if string.len(corto) > 44 then corto = string.sub(corto, 1, 41) .."..." end
	return corto
end
ORIGEN = {}
ORIGEN_DIR = {}   -- real directory where the game was found (PS2)

--- True if the path is on a drive mounted by ata_bd (internal exFAT disk). -----------
function ES_RAIZ_ATA(ruta)
	if ruta == nil then return false end
	local pos = string.find(ruta, ":", 1, true)
	if pos == nil then return false end
	return BDM_ATA[string.sub(ruta, 1, pos)] == true
end

--- True if the given game comes from the internal disk. ------------------------------
function ES_ATA(identidad, nombre)
	if nombre == nil then return false end
	return ES_RAIZ_ATA(ORIGEN[tostring(identidad) .."|".. nombre])
end

--- Full path resolved against the first root that contains it. ------------------------
function RUTA(rel)
	return RAIZ(rel) .. rel
end
