# Name of loaded config, to show to user
name = "Patch memory buffer overrun - 256 bytes"

# These games have IOP memory buffer overrun issues
# Load patch module that fixes this game bug
[[module]]
file = "patch_membo.irx"
load_order = 31
#args = ["1"] # number of 256 byte blocks of guard band to add after each IOP memory allocation (0-9, default 1)
env = ["EE"]
