-- Generated by HelperScripts/BuildSystems.py from the .info files of the
-- cores in LibretroPS2Files/cores, plus the fixed PlayStation entries.
-- Do not edit: re-run the script instead.
-- 61 cores, 68 systems.
--
-- SYSTEMS[folder] = {
--     name     display name, libretro database spelling
--     folder   the key, also the Roms/ folder name (Batocera spelling)
--     roots    where to scan: { path, at = "launcher" | "drive" }
--     ext      every extension any backend of the system accepts
--     backends { kind, id, name, ext }  kind: retroarch|pops|ember|neutrino|opl
--     default  id of the backend used unless a config override says otherwise
-- }
SYSTEMS = {}

SYSTEMS["2048"] = {
	name     = "2048",
	folder   = "2048",
	roots    = {
		{ path = "Roms/2048", at = "launcher" },
	},
	ext      = {".zip"},
	backends = {
		{ kind = "retroarch", id = "2048", name = "2048", ext = {} },
	},
	default  = "2048",
}

SYSTEMS["anarch"] = {
	name     = "Anarch",
	folder   = "anarch",
	roots    = {
		{ path = "Roms/anarch", at = "launcher" },
	},
	ext      = {".zip"},
	backends = {
		{ kind = "retroarch", id = "anarch", name = "anarch", ext = {} },
	},
	default  = "anarch",
}

SYSTEMS["arcadia"] = {
	name     = "Emerson - Arcadia 2001",
	folder   = "arcadia",
	roots    = {
		{ path = "Roms/arcadia", at = "launcher" },
	},
	ext      = {".bin", ".tvc", ".zip"},
	backends = {
		{ kind = "retroarch", id = "amiarcadia", name = "AmiArcadia", ext = {".bin", ".tvc"} },
	},
	default  = "amiarcadia",
}

SYSTEMS["arduboy"] = {
	name     = "Arduboy Inc - Arduboy",
	folder   = "arduboy",
	roots    = {
		{ path = "Roms/arduboy", at = "launcher" },
	},
	ext      = {".arduboy", ".hex", ".zip"},
	backends = {
		{ kind = "retroarch", id = "ardens", name = "Ardens", ext = {".hex", ".arduboy"} },
		{ kind = "retroarch", id = "arduous", name = "Arduous", ext = {".hex"} },
	},
	default  = "ardens",
}

SYSTEMS["atari2600"] = {
	name     = "Atari - 2600",
	folder   = "atari2600",
	roots    = {
		{ path = "Roms/atari2600", at = "launcher" },
	},
	ext      = {".a26", ".bin", ".zip"},
	backends = {
		{ kind = "retroarch", id = "stella2014", name = "Stella 2014", ext = {".a26", ".bin"} },
		{ kind = "retroarch", id = "tia", name = "Tia", ext = {".a26", ".bin"} },
	},
	default  = "stella2014",
}

SYSTEMS["atari5200"] = {
	name     = "Atari - 5200",
	folder   = "atari5200",
	roots    = {
		{ path = "Roms/atari5200", at = "launcher" },
	},
	ext      = {".a52", ".atr", ".atx", ".bin", ".car", ".cas", ".com", ".dcm", ".m3u", ".rom", ".xex", ".xfd", ".zip"},
	backends = {
		{ kind = "retroarch", id = "atari800", name = "Atari800", ext = {".xfd", ".atr", ".dcm", ".cas", ".bin", ".a52", ".zip", ".atx", ".car", ".rom", ".com", ".xex", ".m3u"} },
	},
	default  = "atari800",
}

SYSTEMS["atari800"] = {
	name     = "Atari - 8-bit Family",
	folder   = "atari800",
	roots    = {
		{ path = "Roms/atari800", at = "launcher" },
	},
	ext      = {".a52", ".atr", ".atx", ".bin", ".car", ".cas", ".com", ".dcm", ".m3u", ".rom", ".xex", ".xfd", ".zip"},
	backends = {
		{ kind = "retroarch", id = "atari800", name = "Atari800", ext = {".xfd", ".atr", ".dcm", ".cas", ".bin", ".a52", ".zip", ".atx", ".car", ".rom", ".com", ".xex", ".m3u"} },
	},
	default  = "atari800",
}

SYSTEMS["bk"] = {
	name     = "BK-0010/BK-0011",
	folder   = "bk",
	roots    = {
		{ path = "Roms/bk", at = "launcher" },
	},
	ext      = {".bin", ".zip"},
	backends = {
		{ kind = "retroarch", id = "bk", name = "bk", ext = {".bin"} },
	},
	default  = "bk",
}

SYSTEMS["cassettevision"] = {
	name     = "Epoch - Cassette Vision",
	folder   = "cassettevision",
	roots    = {
		{ path = "Roms/cassettevision", at = "launcher" },
	},
	ext      = {".bin777", ".ptn777", ".zip"},
	backends = {
		{ kind = "retroarch", id = "pd777", name = "PD777", ext = {".zip", ".bin777", ".ptn777"} },
	},
	default  = "pd777",
}

SYSTEMS["cavestory"] = {
	name     = "Cave Story",
	folder   = "cavestory",
	roots    = {
		{ path = "Roms/cavestory", at = "launcher" },
	},
	ext      = {".exe", ".zip"},
	backends = {
		{ kind = "retroarch", id = "nxengine", name = "NXEngine", ext = {".exe"} },
	},
	default  = "nxengine",
}

SYSTEMS["channelf"] = {
	name     = "Fairchild - Channel F",
	folder   = "channelf",
	roots    = {
		{ path = "Roms/channelf", at = "launcher" },
	},
	ext      = {".bin", ".chf", ".zip"},
	backends = {
		{ kind = "retroarch", id = "freechaf", name = "FreeChaF", ext = {".bin", ".chf"} },
	},
	default  = "freechaf",
}

SYSTEMS["chip8"] = {
	name     = "CHIP-8",
	folder   = "chip8",
	roots    = {
		{ path = "Roms/chip8", at = "launcher" },
	},
	ext      = {".ch8", ".sc8", ".xo8", ".zip"},
	backends = {
		{ kind = "retroarch", id = "jaxe", name = "JAXE", ext = {".ch8", ".sc8", ".xo8"} },
	},
	default  = "jaxe",
}

SYSTEMS["colecovision"] = {
	name     = "Coleco - ColecoVision",
	folder   = "colecovision",
	roots    = {
		{ path = "Roms/colecovision", at = "launcher" },
	},
	ext      = {".bin", ".cas", ".col", ".cv", ".dsk", ".m3u", ".mx1", ".mx2", ".ri", ".rom", ".sc", ".sf", ".sg", ".zip"},
	backends = {
		{ kind = "retroarch", id = "bluemsx", name = "blueMSX", ext = {".rom", ".ri", ".mx1", ".mx2", ".dsk", ".col", ".sg", ".sc", ".sf", ".cas", ".m3u"} },
		{ kind = "retroarch", id = "gearcoleco", name = "Gearcoleco", ext = {".col", ".cv", ".bin", ".rom"} },
	},
	default  = "gearcoleco",
}

SYSTEMS["dice"] = {
	name     = "DICE",
	folder   = "dice",
	roots    = {
		{ path = "Roms/dice", at = "launcher" },
	},
	ext      = {".1da", ".4c", ".4d", ".6c", ".a1", ".a4", ".c4", ".c6", ".d2", ".d4", ".d7", ".da1", ".dmy", ".f4", ".k1", ".s1", ".zip"},
	backends = {
		{ kind = "retroarch", id = "dice", name = "DICE", ext = {".zip", ".dmy", ".k1", ".a1", ".6c", ".c6", ".d2", ".s1", ".f4", ".a4", ".1da", ".da1", ".c4", ".4c", ".4d", ".d7", ".d4"} },
	},
	default  = "dice",
}

SYSTEMS["doom"] = {
	name     = "DOOM",
	folder   = "doom",
	roots    = {
		{ path = "Roms/doom", at = "launcher" },
	},
	ext      = {".iwad", ".pwad", ".wad", ".zip"},
	backends = {
		{ kind = "retroarch", id = "prboom", name = "PrBoom", ext = {".wad", ".iwad", ".pwad"} },
	},
	default  = "prboom",
}

SYSTEMS["elektor"] = {
	name     = "Elektor - TV Games Computer",
	folder   = "elektor",
	roots    = {
		{ path = "Roms/elektor", at = "launcher" },
	},
	ext      = {".bin", ".tvc", ".zip"},
	backends = {
		{ kind = "retroarch", id = "amiarcadia", name = "AmiArcadia", ext = {".bin", ".tvc"} },
	},
	default  = "amiarcadia",
}

SYSTEMS["fds"] = {
	name     = "Nintendo - Family Computer Disk System",
	folder   = "fds",
	roots    = {
		{ path = "Roms/fds", at = "launcher" },
	},
	ext      = {".fds", ".nes", ".unf", ".unif", ".zip"},
	backends = {
		{ kind = "retroarch", id = "fceumm", name = "FCEUmm", ext = {".fds", ".nes", ".unif", ".unf"} },
	},
	default  = "fceumm",
}

SYSTEMS["gam4980"] = {
	name     = "gam4980",
	folder   = "gam4980",
	roots    = {
		{ path = "Roms/gam4980", at = "launcher" },
	},
	ext      = {".gam", ".zip"},
	backends = {
		{ kind = "retroarch", id = "gam4980", name = "gam4980", ext = {".gam"} },
	},
	default  = "gam4980",
}

SYSTEMS["gamegear"] = {
	name     = "Sega - Game Gear",
	folder   = "gamegear",
	roots    = {
		{ path = "Roms/gamegear", at = "launcher" },
	},
	ext      = {".32x", ".68k", ".bin", ".chd", ".col", ".cue", ".gen", ".gg", ".iso", ".m3u", ".md", ".pco", ".rom", ".sc", ".sg", ".sgd", ".smd", ".sms", ".zip"},
	backends = {
		{ kind = "retroarch", id = "gearsystem", name = "Gearsystem", ext = {".sms", ".gg", ".sg", ".bin", ".rom"} },
		{ kind = "retroarch", id = "picodrive", name = "PicoDrive", ext = {".bin", ".gen", ".smd", ".md", ".32x", ".cue", ".iso", ".chd", ".sms", ".gg", ".sg", ".sc", ".m3u", ".68k", ".sgd", ".pco"} },
		{ kind = "retroarch", id = "smsplus", name = "SMS Plus GX", ext = {".sms", ".bin", ".rom", ".col", ".gg", ".sg"} },
	},
	default  = "gearsystem",
}

SYSTEMS["gb"] = {
	name     = "Nintendo - Game Boy",
	folder   = "gb",
	roots    = {
		{ path = "Roms/gb", at = "launcher" },
	},
	ext      = {".cgb", ".dmg", ".gb", ".gba", ".gbc", ".sgb", ".zip"},
	backends = {
		{ kind = "retroarch", id = "DoubleCherryGB", name = "DoubleCherryGB", ext = {".cgb", ".dmg", ".gb", ".gbc", ".sgb"} },
		{ kind = "retroarch", id = "gambatte", name = "Gambatte", ext = {".gb", ".gbc", ".dmg"} },
		{ kind = "retroarch", id = "gearboy", name = "Gearboy", ext = {".gb", ".dmg", ".gbc", ".cgb", ".sgb"} },
		{ kind = "retroarch", id = "mgba", name = "mGBA", ext = {".gb", ".gbc", ".gba"} },
		{ kind = "retroarch", id = "tgbdual", name = "TGB Dual", ext = {".cgb", ".dmg", ".gb", ".gbc", ".sgb"} },
	},
	default  = "gambatte",
}

SYSTEMS["gba"] = {
	name     = "Nintendo - Game Boy Advance",
	folder   = "gba",
	roots    = {
		{ path = "Roms/gba", at = "launcher" },
	},
	ext      = {".bin", ".gb", ".gba", ".gbc", ".zip"},
	backends = {
		{ kind = "retroarch", id = "gpsp", name = "gpSP", ext = {".gba", ".bin"} },
		{ kind = "retroarch", id = "mgba", name = "mGBA", ext = {".gb", ".gbc", ".gba"} },
	},
	default  = "mgba",
}

SYSTEMS["gbc"] = {
	name     = "Nintendo - Game Boy Color",
	folder   = "gbc",
	roots    = {
		{ path = "Roms/gbc", at = "launcher" },
	},
	ext      = {".cgb", ".dmg", ".gb", ".gba", ".gbc", ".sgb", ".zip"},
	backends = {
		{ kind = "retroarch", id = "DoubleCherryGB", name = "DoubleCherryGB", ext = {".cgb", ".dmg", ".gb", ".gbc", ".sgb"} },
		{ kind = "retroarch", id = "gambatte", name = "Gambatte", ext = {".gb", ".gbc", ".dmg"} },
		{ kind = "retroarch", id = "gearboy", name = "Gearboy", ext = {".gb", ".dmg", ".gbc", ".cgb", ".sgb"} },
		{ kind = "retroarch", id = "mgba", name = "mGBA", ext = {".gb", ".gbc", ".gba"} },
		{ kind = "retroarch", id = "tgbdual", name = "TGB Dual", ext = {".cgb", ".dmg", ".gb", ".gbc", ".sgb"} },
	},
	default  = "gambatte",
}

SYSTEMS["gong"] = {
	name     = "Pong Game Clone",
	folder   = "gong",
	roots    = {
		{ path = "Roms/gong", at = "launcher" },
	},
	ext      = {".zip"},
	backends = {
		{ kind = "retroarch", id = "gong", name = "Gong", ext = {} },
	},
	default  = "gong",
}

SYSTEMS["intellivision"] = {
	name     = "Mattel - Intellivision",
	folder   = "intellivision",
	roots    = {
		{ path = "Roms/intellivision", at = "launcher" },
	},
	ext      = {".bin", ".int", ".rom", ".zip"},
	backends = {
		{ kind = "retroarch", id = "freeintv", name = "FreeIntv", ext = {".int", ".bin", ".rom"} },
	},
	default  = "freeintv",
}

SYSTEMS["j2me"] = {
	name     = "J2ME",
	folder   = "j2me",
	roots    = {
		{ path = "Roms/j2me", at = "launcher" },
	},
	ext      = {".adf", ".jad", ".jam", ".jar", ".kjx", ".sec", ".sp", ".sp0", ".sp1", ".sp2", ".sp3", ".sp4", ".sp5", ".sp6", ".sp7", ".sp8", ".sp9", ".sqc", ".sto", ".zip"},
	backends = {
		{ kind = "retroarch", id = "squirreljme", name = "SquirrelJME", ext = {".jar", ".sqc", ".jam", ".jad", ".kjx", ".adf", ".sec", ".sto", ".sp", ".sp0", ".sp1", ".sp2", ".sp3", ".sp4", ".sp5", ".sp6", ".sp7", ".sp8", ".sp9"} },
	},
	default  = "squirreljme",
}

SYSTEMS["jumpnbump"] = {
	name     = "Jump 'n Bump",
	folder   = "jumpnbump",
	roots    = {
		{ path = "Roms/jumpnbump", at = "launcher" },
	},
	ext      = {".dat", ".zip"},
	backends = {
		{ kind = "retroarch", id = "jumpnbump", name = "jumpnbump", ext = {".dat"} },
	},
	default  = "jumpnbump",
}

SYSTEMS["lowresnx"] = {
	name     = "LowRes NX",
	folder   = "lowresnx",
	roots    = {
		{ path = "Roms/lowresnx", at = "launcher" },
	},
	ext      = {".nx", ".zip"},
	backends = {
		{ kind = "retroarch", id = "lowresnx", name = "lowresnx", ext = {".nx"} },
	},
	default  = "lowresnx",
}

SYSTEMS["lutro"] = {
	name     = "Lutro",
	folder   = "lutro",
	roots    = {
		{ path = "Roms/lutro", at = "launcher" },
	},
	ext      = {".love", ".lua", ".lutro", ".zip"},
	backends = {
		{ kind = "retroarch", id = "lutro", name = "Lutro", ext = {".lutro", ".love", ".lua"} },
	},
	default  = "lutro",
}

SYSTEMS["lynx"] = {
	name     = "Atari - Lynx",
	folder   = "lynx",
	roots    = {
		{ path = "Roms/lynx", at = "launcher" },
	},
	ext      = {".bll", ".lnx", ".lyx", ".o", ".zip"},
	backends = {
		{ kind = "retroarch", id = "gearlynx", name = "Gearlynx", ext = {".lnx", ".lyx", ".o"} },
		{ kind = "retroarch", id = "handy", name = "Handy", ext = {".lnx", ".lyx", ".o"} },
		{ kind = "retroarch", id = "mednafen_lynx", name = "Beetle Lynx", ext = {".lnx", ".lyx", ".bll", ".o"} },
	},
	default  = "handy",
}

SYSTEMS["macintosh"] = {
	name     = "Mac68k",
	folder   = "macintosh",
	roots    = {
		{ path = "Roms/macintosh", at = "launcher" },
	},
	ext      = {".cmd", ".dsk", ".hvf", ".img", ".zip"},
	backends = {
		{ kind = "retroarch", id = "minivmac", name = "MinivmacII", ext = {".dsk", ".img", ".zip", ".hvf", ".cmd"} },
	},
	default  = "minivmac",
}

SYSTEMS["mastersystem"] = {
	name     = "Sega - Master System - Mark III",
	folder   = "mastersystem",
	roots    = {
		{ path = "Roms/mastersystem", at = "launcher" },
	},
	ext      = {".32x", ".68k", ".bin", ".chd", ".col", ".cue", ".gen", ".gg", ".iso", ".m3u", ".md", ".pco", ".rom", ".sc", ".sg", ".sgd", ".smd", ".sms", ".zip"},
	backends = {
		{ kind = "retroarch", id = "gearsystem", name = "Gearsystem", ext = {".sms", ".gg", ".sg", ".bin", ".rom"} },
		{ kind = "retroarch", id = "picodrive", name = "PicoDrive", ext = {".bin", ".gen", ".smd", ".md", ".32x", ".cue", ".iso", ".chd", ".sms", ".gg", ".sg", ".sc", ".m3u", ".68k", ".sgd", ".pco"} },
		{ kind = "retroarch", id = "smsplus", name = "SMS Plus GX", ext = {".sms", ".bin", ".rom", ".col", ".gg", ".sg"} },
	},
	default  = "gearsystem",
}

SYSTEMS["megadrive"] = {
	name     = "Sega - Mega Drive - Genesis",
	folder   = "megadrive",
	roots    = {
		{ path = "Roms/megadrive", at = "launcher" },
	},
	ext      = {".32x", ".68k", ".bin", ".chd", ".cue", ".gen", ".gg", ".iso", ".m3u", ".md", ".pco", ".sc", ".sg", ".sgd", ".smd", ".sms", ".zip"},
	backends = {
		{ kind = "retroarch", id = "picodrive", name = "PicoDrive", ext = {".bin", ".gen", ".smd", ".md", ".32x", ".cue", ".iso", ".chd", ".sms", ".gg", ".sg", ".sc", ".m3u", ".68k", ".sgd", ".pco"} },
	},
	default  = "picodrive",
}

SYSTEMS["microw8"] = {
	name     = "MicroW8",
	folder   = "microw8",
	roots    = {
		{ path = "Roms/microw8", at = "launcher" },
	},
	ext      = {".uw8", ".wasm", ".zip"},
	backends = {
		{ kind = "retroarch", id = "uw8", name = "MicroW8", ext = {".uw8", ".wasm"} },
	},
	default  = "uw8",
}

SYSTEMS["mrboom"] = {
	name     = "MrBoom",
	folder   = "mrboom",
	roots    = {
		{ path = "Roms/mrboom", at = "launcher" },
	},
	ext      = {".desktop", ".zip"},
	backends = {
		{ kind = "retroarch", id = "mrboom", name = "Mr.Boom", ext = {".desktop"} },
	},
	default  = "mrboom",
}

SYSTEMS["msx1"] = {
	name     = "Microsoft - MSX",
	folder   = "msx1",
	roots    = {
		{ path = "Roms/msx1", at = "launcher" },
	},
	ext      = {".cas", ".col", ".dsk", ".fdi", ".m3u", ".mx1", ".mx2", ".ri", ".rom", ".sc", ".sf", ".sg", ".zip"},
	backends = {
		{ kind = "retroarch", id = "bluemsx", name = "blueMSX", ext = {".rom", ".ri", ".mx1", ".mx2", ".dsk", ".col", ".sg", ".sc", ".sf", ".cas", ".m3u"} },
		{ kind = "retroarch", id = "fmsx", name = "fMSX", ext = {".rom", ".mx1", ".mx2", ".dsk", ".fdi", ".cas", ".m3u"} },
	},
	default  = "fmsx",
}

SYSTEMS["msx2"] = {
	name     = "Microsoft - MSX2",
	folder   = "msx2",
	roots    = {
		{ path = "Roms/msx2", at = "launcher" },
	},
	ext      = {".cas", ".col", ".dsk", ".fdi", ".m3u", ".mx1", ".mx2", ".ri", ".rom", ".sc", ".sf", ".sg", ".zip"},
	backends = {
		{ kind = "retroarch", id = "bluemsx", name = "blueMSX", ext = {".rom", ".ri", ".mx1", ".mx2", ".dsk", ".col", ".sg", ".sc", ".sf", ".cas", ".m3u"} },
		{ kind = "retroarch", id = "fmsx", name = "fMSX", ext = {".rom", ".mx1", ".mx2", ".dsk", ".fdi", ".cas", ".m3u"} },
	},
	default  = "fmsx",
}

SYSTEMS["music"] = {
	name     = "Music",
	folder   = "music",
	roots    = {
		{ path = "Roms/music", at = "launcher" },
	},
	ext      = {".ay", ".cdg", ".gbs", ".gym", ".hes", ".kss", ".nsf", ".nsfe", ".sap", ".spc", ".vgm", ".vgz", ".zip"},
	backends = {
		{ kind = "retroarch", id = "gme", name = "Game Music Emu", ext = {".ay", ".gbs", ".gym", ".hes", ".kss", ".nsf", ".nsfe", ".sap", ".spc", ".vgm", ".vgz", ".zip"} },
		{ kind = "retroarch", id = "pocketcdg", name = "PocketCDG", ext = {".cdg"} },
	},
	default  = "gme",
}

SYSTEMS["neogeocd"] = {
	name     = "SNK - Neo Geo CD",
	folder   = "neogeocd",
	roots    = {
		{ path = "Roms/neogeocd", at = "launcher" },
	},
	ext      = {".chd", ".cue", ".zip"},
	backends = {
		{ kind = "retroarch", id = "neocd", name = "NeoCD", ext = {".cue", ".chd"} },
	},
	default  = "neocd",
}

SYSTEMS["nes"] = {
	name     = "Nintendo - Nintendo Entertainment System",
	folder   = "nes",
	roots    = {
		{ path = "Roms/nes", at = "launcher" },
	},
	ext      = {".fds", ".nes", ".unf", ".unif", ".zip"},
	backends = {
		{ kind = "retroarch", id = "fceumm", name = "FCEUmm", ext = {".fds", ".nes", ".unif", ".unf"} },
		{ kind = "retroarch", id = "quicknes", name = "QuickNES", ext = {".nes"} },
	},
	default  = "fceumm",
}

SYSTEMS["ngp"] = {
	name     = "SNK - Neo Geo Pocket",
	folder   = "ngp",
	roots    = {
		{ path = "Roms/ngp", at = "launcher" },
	},
	ext      = {".ngc", ".ngp", ".ngpc", ".npc", ".zip"},
	backends = {
		{ kind = "retroarch", id = "race", name = "RACE", ext = {".ngp", ".ngc", ".ngpc", ".npc"} },
	},
	default  = "race",
}

SYSTEMS["ngpc"] = {
	name     = "SNK - Neo Geo Pocket Color",
	folder   = "ngpc",
	roots    = {
		{ path = "Roms/ngpc", at = "launcher" },
	},
	ext      = {".ngc", ".ngp", ".ngpc", ".npc", ".zip"},
	backends = {
		{ kind = "retroarch", id = "race", name = "RACE", ext = {".ngp", ".ngc", ".ngpc", ".npc"} },
	},
	default  = "race",
}

SYSTEMS["o2em"] = {
	name     = "Magnavox - Odyssey2",
	folder   = "o2em",
	roots    = {
		{ path = "Roms/o2em", at = "launcher" },
	},
	ext      = {".bin", ".zip"},
	backends = {
		{ kind = "retroarch", id = "o2em", name = "O2EM", ext = {".bin"} },
	},
	default  = "o2em",
}

SYSTEMS["palm"] = {
	name     = "Palm OS",
	folder   = "palm",
	roots    = {
		{ path = "Roms/palm", at = "launcher" },
	},
	ext      = {".img", ".pdb", ".pqa", ".prc", ".zip"},
	backends = {
		{ kind = "retroarch", id = "mu", name = "Mu", ext = {".prc", ".pqa", ".img", ".pdb", ".zip"} },
	},
	default  = "mu",
}

SYSTEMS["pc88"] = {
	name     = "NEC - PC-8001 - PC-8801",
	folder   = "pc88",
	roots    = {
		{ path = "Roms/pc88", at = "launcher" },
	},
	ext      = {".d88", ".m3u", ".u88", ".zip"},
	backends = {
		{ kind = "retroarch", id = "quasi88", name = "QUASI88", ext = {".d88", ".u88", ".m3u"} },
	},
	default  = "quasi88",
}

SYSTEMS["pico"] = {
	name     = "Sega - PICO",
	folder   = "pico",
	roots    = {
		{ path = "Roms/pico", at = "launcher" },
	},
	ext      = {".32x", ".68k", ".bin", ".chd", ".cue", ".gen", ".gg", ".iso", ".m3u", ".md", ".pco", ".sc", ".sg", ".sgd", ".smd", ".sms", ".zip"},
	backends = {
		{ kind = "retroarch", id = "picodrive", name = "PicoDrive", ext = {".bin", ".gen", ".smd", ".md", ".32x", ".cue", ".iso", ".chd", ".sms", ".gg", ".sg", ".sc", ".m3u", ".68k", ".sgd", ".pco"} },
	},
	default  = "picodrive",
}

SYSTEMS["pico8"] = {
	name     = "PICO-8",
	folder   = "pico8",
	roots    = {
		{ path = "Roms/pico8", at = "launcher" },
	},
	ext      = {".p8", ".png", ".zip"},
	backends = {
		{ kind = "retroarch", id = "retro8", name = "Retro8", ext = {".p8", ".png"} },
	},
	default  = "retro8",
}

SYSTEMS["ps1"] = {
	name     = "Sony - PlayStation",
	folder   = "ps1",
	roots    = {
		{ path = "Roms/ps1", at = "launcher" },
		{ path = "Roms/ps1/games", at = "launcher" },
		{ path = "POPS", at = "drive" },
	},
	ext      = {".bin", ".cue", ".vcd"},
	backends = {
		{ kind = "pops", id = "pops", name = "POPStarter", ext = {".vcd"} },
		{ kind = "ember", id = "ember", name = "Ember", ext = {".cue", ".bin"} },
	},
	default  = "pops",
}

SYSTEMS["ps2"] = {
	name     = "Sony - PlayStation 2",
	folder   = "ps2",
	roots    = {
		{ path = "DVD", at = "drive" },
		{ path = "CD", at = "drive" },
	},
	ext      = {".iso"},
	backends = {
		{ kind = "neutrino", id = "neutrino", name = "Neutrino", ext = {".iso"} },
		{ kind = "opl", id = "opl", name = "OPL", ext = {".iso"} },
	},
	default  = "neutrino",
}

SYSTEMS["satellaview"] = {
	name     = "Nintendo - Satellaview",
	folder   = "satellaview",
	roots    = {
		{ path = "Roms/satellaview", at = "launcher" },
	},
	ext      = {".bsx", ".dx2", ".fig", ".gd3", ".gd7", ".sfc", ".smc", ".swc", ".zip"},
	backends = {
		{ kind = "retroarch", id = "snes9x2002", name = "Snes9x 2002", ext = {".smc", ".fig", ".sfc", ".gd3", ".gd7", ".dx2", ".bsx", ".swc"} },
	},
	default  = "snes9x2002",
}

SYSTEMS["sega32x"] = {
	name     = "Sega - 32X",
	folder   = "sega32x",
	roots    = {
		{ path = "Roms/sega32x", at = "launcher" },
	},
	ext      = {".32x", ".68k", ".bin", ".chd", ".cue", ".gen", ".gg", ".iso", ".m3u", ".md", ".pco", ".sc", ".sg", ".sgd", ".smd", ".sms", ".zip"},
	backends = {
		{ kind = "retroarch", id = "picodrive", name = "PicoDrive", ext = {".bin", ".gen", ".smd", ".md", ".32x", ".cue", ".iso", ".chd", ".sms", ".gg", ".sg", ".sc", ".m3u", ".68k", ".sgd", ".pco"} },
	},
	default  = "picodrive",
}

SYSTEMS["segacd"] = {
	name     = "Sega - Mega-CD - Sega CD",
	folder   = "segacd",
	roots    = {
		{ path = "Roms/segacd", at = "launcher" },
	},
	ext      = {".32x", ".68k", ".bin", ".chd", ".cue", ".gen", ".gg", ".iso", ".m3u", ".md", ".pco", ".sc", ".sg", ".sgd", ".smd", ".sms", ".zip"},
	backends = {
		{ kind = "retroarch", id = "picodrive", name = "PicoDrive", ext = {".bin", ".gen", ".smd", ".md", ".32x", ".cue", ".iso", ".chd", ".sms", ".gg", ".sg", ".sc", ".m3u", ".68k", ".sgd", ".pco"} },
	},
	default  = "picodrive",
}

SYSTEMS["sg1000"] = {
	name     = "Sega - SG-1000",
	folder   = "sg1000",
	roots    = {
		{ path = "Roms/sg1000", at = "launcher" },
	},
	ext      = {".bin", ".cas", ".col", ".dsk", ".gg", ".m3u", ".mx1", ".mx2", ".ri", ".rom", ".sc", ".sf", ".sg", ".sms", ".zip"},
	backends = {
		{ kind = "retroarch", id = "bluemsx", name = "blueMSX", ext = {".rom", ".ri", ".mx1", ".mx2", ".dsk", ".col", ".sg", ".sc", ".sf", ".cas", ".m3u"} },
		{ kind = "retroarch", id = "gearsystem", name = "Gearsystem", ext = {".sms", ".gg", ".sg", ".bin", ".rom"} },
	},
	default  = "gearsystem",
}

SYSTEMS["snes"] = {
	name     = "Nintendo - Super Nintendo Entertainment System",
	folder   = "snes",
	roots    = {
		{ path = "Roms/snes", at = "launcher" },
	},
	ext      = {".bsx", ".dx2", ".fig", ".gd3", ".gd7", ".sfc", ".smc", ".swc", ".zip"},
	backends = {
		{ kind = "retroarch", id = "snes9x2002", name = "Snes9x 2002", ext = {".smc", ".fig", ".sfc", ".gd3", ".gd7", ".dx2", ".bsx", ".swc"} },
	},
	default  = "snes9x2002",
}

SYSTEMS["spectravideo"] = {
	name     = "Spectravideo - SVI-318 - SVI-328",
	folder   = "spectravideo",
	roots    = {
		{ path = "Roms/spectravideo", at = "launcher" },
	},
	ext      = {".cas", ".col", ".dsk", ".m3u", ".mx1", ".mx2", ".ri", ".rom", ".sc", ".sf", ".sg", ".zip"},
	backends = {
		{ kind = "retroarch", id = "bluemsx", name = "blueMSX", ext = {".rom", ".ri", ".mx1", ".mx2", ".dsk", ".col", ".sg", ".sc", ".sf", ".cas", ".m3u"} },
	},
	default  = "bluemsx",
}

SYSTEMS["sufami"] = {
	name     = "Nintendo - Sufami Turbo",
	folder   = "sufami",
	roots    = {
		{ path = "Roms/sufami", at = "launcher" },
	},
	ext      = {".bsx", ".dx2", ".fig", ".gd3", ".gd7", ".sfc", ".smc", ".swc", ".zip"},
	backends = {
		{ kind = "retroarch", id = "snes9x2002", name = "Snes9x 2002", ext = {".smc", ".fig", ".sfc", ".gd3", ".gd7", ".dx2", ".bsx", ".swc"} },
	},
	default  = "snes9x2002",
}

SYSTEMS["tamagotchi"] = {
	name     = "Tamagotchi P1",
	folder   = "tamagotchi",
	roots    = {
		{ path = "Roms/tamagotchi", at = "launcher" },
	},
	ext      = {".b", ".bin", ".rom", ".zip"},
	backends = {
		{ kind = "retroarch", id = "tamalibretro", name = "TamaLIBretro", ext = {".b", ".bin", ".rom"} },
	},
	default  = "tamalibretro",
}

SYSTEMS["thomson"] = {
	name     = "Thomson - MOTO",
	folder   = "thomson",
	roots    = {
		{ path = "Roms/thomson", at = "launcher" },
	},
	ext      = {".fd", ".k7", ".m5", ".m7", ".rom", ".sap", ".zip"},
	backends = {
		{ kind = "retroarch", id = "theodore", name = "theodore", ext = {".fd", ".sap", ".k7", ".m7", ".m5", ".rom"} },
	},
	default  = "theodore",
}

SYSTEMS["ti83"] = {
	name     = "TI83",
	folder   = "ti83",
	roots    = {
		{ path = "Roms/ti83", at = "launcher" },
	},
	ext      = {".8xg", ".8xk", ".8xp", ".zip"},
	backends = {
		{ kind = "retroarch", id = "numero", name = "Numero", ext = {".8xp", ".8xk", ".8xg"} },
	},
	default  = "numero",
}

SYSTEMS["uzebox"] = {
	name     = "Uzebox",
	folder   = "uzebox",
	roots    = {
		{ path = "Roms/uzebox", at = "launcher" },
	},
	ext      = {".uze", ".zip"},
	backends = {
		{ kind = "retroarch", id = "uzem", name = "uzem", ext = {".uze"} },
	},
	default  = "uzem",
}

SYSTEMS["vaporspec"] = {
	name     = "VaporSpec",
	folder   = "vaporspec",
	roots    = {
		{ path = "Roms/vaporspec", at = "launcher" },
	},
	ext      = {".vaporbin", ".zip"},
	backends = {
		{ kind = "retroarch", id = "vaporspec", name = "VaporSpec", ext = {".vaporbin"} },
	},
	default  = "vaporspec",
}

SYSTEMS["vc4000"] = {
	name     = "Interton - VC 4000",
	folder   = "vc4000",
	roots    = {
		{ path = "Roms/vc4000", at = "launcher" },
	},
	ext      = {".bin", ".tvc", ".zip"},
	backends = {
		{ kind = "retroarch", id = "amiarcadia", name = "AmiArcadia", ext = {".bin", ".tvc"} },
	},
	default  = "amiarcadia",
}

SYSTEMS["videopacplus"] = {
	name     = "Philips - Videopac+",
	folder   = "videopacplus",
	roots    = {
		{ path = "Roms/videopacplus", at = "launcher" },
	},
	ext      = {".bin", ".zip"},
	backends = {
		{ kind = "retroarch", id = "o2em", name = "O2EM", ext = {".bin"} },
	},
	default  = "o2em",
}

SYSTEMS["wasm4"] = {
	name     = "WASM-4",
	folder   = "wasm4",
	roots    = {
		{ path = "Roms/wasm4", at = "launcher" },
	},
	ext      = {".wasm", ".zip"},
	backends = {
		{ kind = "retroarch", id = "wasm4", name = "WASM-4", ext = {".wasm"} },
	},
	default  = "wasm4",
}

SYSTEMS["wolf3d"] = {
	name     = "Wolfenstein 3D",
	folder   = "wolf3d",
	roots    = {
		{ path = "Roms/wolf3d", at = "launcher" },
	},
	ext      = {".exe", ".n3d", ".pk3", ".sdm", ".sod", ".wl1", ".wl6", ".zip"},
	backends = {
		{ kind = "retroarch", id = "ecwolf", name = "ECWolf", ext = {".wl6", ".n3d", ".sod", ".sdm", ".wl1", ".pk3", ".exe"} },
	},
	default  = "ecwolf",
}

SYSTEMS["wswan"] = {
	name     = "Bandai - WonderSwan",
	folder   = "wswan",
	roots    = {
		{ path = "Roms/wswan", at = "launcher" },
	},
	ext      = {".pc2", ".pcv2", ".ws", ".wsc", ".zip"},
	backends = {
		{ kind = "retroarch", id = "mednafen_wswan", name = "Beetle WonderSwan", ext = {".ws", ".wsc", ".pc2", ".pcv2"} },
	},
	default  = "mednafen_wswan",
}

SYSTEMS["wswanc"] = {
	name     = "Bandai - WonderSwan Color",
	folder   = "wswanc",
	roots    = {
		{ path = "Roms/wswanc", at = "launcher" },
	},
	ext      = {".pc2", ".pcv2", ".ws", ".wsc", ".zip"},
	backends = {
		{ kind = "retroarch", id = "mednafen_wswan", name = "Beetle WonderSwan", ext = {".ws", ".wsc", ".pc2", ".pcv2"} },
	},
	default  = "mednafen_wswan",
}

SYSTEMS["x1"] = {
	name     = "Sharp - X1",
	folder   = "x1",
	roots    = {
		{ path = "Roms/x1", at = "launcher" },
	},
	ext      = {".2d", ".2hd", ".88d", ".cmd", ".d88", ".dup", ".dx1", ".hdm", ".tap", ".tfd", ".xdf", ".zip"},
	backends = {
		{ kind = "retroarch", id = "x1", name = "x1", ext = {".dx1", ".zip", ".2d", ".2hd", ".tfd", ".d88", ".88d", ".hdm", ".xdf", ".dup", ".tap", ".cmd"} },
	},
	default  = "x1",
}

SYSTEMS["zx81"] = {
	name     = "Sinclair - ZX 81",
	folder   = "zx81",
	roots    = {
		{ path = "Roms/zx81", at = "launcher" },
	},
	ext      = {".p", ".t81", ".tzx", ".zip"},
	backends = {
		{ kind = "retroarch", id = "81", name = "81", ext = {".p", ".tzx", ".t81"} },
	},
	default  = "81",
}

--- The system a folder name belongs to, or nil. ---------------------------------
function system_of_folder(folder)
	if folder == nil then return nil end
	return SYSTEMS[string.lower(folder)]
end

--- The backends able to open a file of a system, the default first. ------------
--- A .zip is accepted by every RetroArch core: RetroArch extracts it itself.
function backends_for(folder, filename)
	local s = SYSTEMS[folder]
	if s == nil then return {} end
	local ext = string.lower(string.match(filename or "", "%.[^%.]+$") or "")
	local out = {}
	for i = 1, #s.backends do
		local b = s.backends[i]
		local ok = (ext == ".zip" and b.kind == "retroarch")
		for j = 1, #b.ext do if b.ext[j] == ext then ok = true end end
		if ok then
			if b.id == s.default then table.insert(out, 1, b) else out[#out + 1] = b end
		end
	end
	return out
end

--- The absolute folders to scan for a system on one drive. -----------------------
--- launcher_dir is e.g. "mass1:/Prism"; the drive is taken from it.
function scan_roots(folder, launcher_dir)
	local s = SYSTEMS[folder]
	if s == nil or launcher_dir == nil then return {} end
	local drive = string.match(launcher_dir, "^[^:]+:") or launcher_dir
	local out = {}
	for i = 1, #s.roots do
		local r = s.roots[i]
		if r.at == "drive" then out[#out + 1] = drive .."/".. r.path
		else out[#out + 1] = launcher_dir .."/".. r.path end
	end
	return out
end
